<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://server.talend.telefonica.de/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://server.talend.telefonica.de/" name="TransactionServerService">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://server.talend.telefonica.de/" schemaLocation="http://localhost:8040/services/appsolute?xsd=1"/>
        </xsd:schema>
        <xsd:schema>
            <xsd:import namespace="/de/telefonica/talend/model" schemaLocation="http://localhost:8040/services/appsolute?xsd=2"/>
        </xsd:schema>
    </types>
    <message name="getTicketInfo">
        <part name="parameters" element="tns:getTicketInfo"/>
    </message>
    <message name="getTicketInfoResponse">
        <part name="parameters" element="tns:getTicketInfoResponse"/>
    </message>
    <portType name="TransactionServer">
        <operation name="getTicketInfo">
            <input wsam:Action="http://server.talend.telefonica.de/TransactionServer/getTicketInfoRequest" message="tns:getTicketInfo"/>
            <output wsam:Action="http://server.talend.telefonica.de/TransactionServer/getTicketInfoResponse" message="tns:getTicketInfoResponse"/>
        </operation>
    </portType>
    <binding name="TransactionServerPortBinding" type="tns:TransactionServer">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="getTicketInfo">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="TransactionServerService">
        <port name="TransactionServerPort" binding="tns:TransactionServerPortBinding">
            <soap:address location="http://localhost:8040/services/appsolute"/>
        </port>
    </service>
</definitions>